;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #dd282a36
foreground = #f8f8f2
primary = #bd93f9
secondary = #8be9fd
alert = #ff5555
disabled = #6272a4

[bar/mibarra]
bottom = true
width = 96%
offset-x = 2%
offset-y = 1%
height = 30
radius = 12

; Fija la barra por encima de las ventanas
override-redirect = false 
wm-restack = i3

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 2
border-size = 0
padding-left = 2
padding-right = 2
module-margin = 1

; Fuentes (necesitas Nerd Fonts instaladas)
font-0 = "FiraCode Nerd Font:size=10;2"
font-1 = "Symbols Nerd Font:size=12;2"

[module/rofi]
type = custom/text
content = "󰣇 "
content-foreground = ${colors.secondary}
click-left = ~/.config/rofi/launchers/type-7/launcher.sh


[module/i3]
type = internal/i3
pin-workspaces = true
show-urgent = true
strip-wsnumbers = true
index-sort = true
format = <label-state> <label-mode>
label-focused = %name%
label-focused-background = #44475a
label-focused-underline= ${colors.primary}
label-focused-padding = 1
label-unfocused = %name%
label-unfocused-padding = 1
label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

[module/screenshot]
type = custom/text
content = " "
content-foreground = ${colors.secondary}
# Al hacer clic, se abre la interfaz de recorte de flameshot
click-left = flameshot gui

[module/date]
type = internal/date
interval = 30
date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S
label =  %date%
label-foreground = ${colors.primary}

[module/cpu]
type = internal/cpu
; Intervalo en 3 para no gastar recursos del i3-5005U
interval = 3
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[module/memory]
type = internal/memory
interval = 3
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/bluetooth]
type = custom/text
content = ""
content-foreground = ${colors.primary}
; Abre blueman para gestionar bluetooth visualmente
click-left = blueman-manager

[module/pulseaudio]
type = internal/pulseaudio

; Esto es clave para que no se dispare a números locos
use-ui-max = false
interval = 5

format-volume = <label-volume>
format-volume-prefix = "  "
format-volume-prefix-foreground = ${colors.primary}

; Forzamos a que el label solo muestre hasta 3 dígitos (máximo 100)
label-volume = %percentage%%

label-muted = "󰝟 Muted"
label-muted-foreground = ${colors.disabled}

click-right = pavucontrol
click-left = pactl set-sink-mute @DEFAULT_SINK@ toggle
[module/backlight]
type = internal/backlight
; Suele ser intel_backlight en ese modelo de Ideapad
card = intel_backlight
use-actual-brightness = true
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage%%

[module/wifi]
type = internal/network
interface-type = wireless
interval = 3
format-connected = <label-connected>
format-connected-prefix = " "
format-connected-prefix-foreground = ${colors.primary}

; Aquí truncamos el nombre: mínimo 1 caracter, máximo 8, y añade "..." si se pasa
label-connected = %essid:1:3:%

format-disconnected = <label-disconnected>
label-disconnected = 󰖪 Desc.
label-disconnected-foreground = ${colors.disabled}

[module/battery]
type = internal/battery
full-at = 99
low-at = 15
; Revisa si tu batería es BAT0 o BAT1 usando: ls /sys/class/power_supply/
battery = BAT0
adapter = AC
poll-interval = 5
format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
label-charging = %percentage%%
label-discharging = %percentage%%
label-full =  %percentage%%
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-foreground = ${colors.primary}
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-foreground = ${colors.secondary}


